config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    authenticated do
      root to: 'tasks#index'
    end
    unauthenticated do
      root to: 'devise/sessions#new', as: nil
    end
  end  

  resources :groups do
    resources :tasks
  end

  resources :tasks do
    resources :groups
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" } 

  resources :users do
    resources :groups
  end

  resources :privacy_and_deletion_policy

  patch "/groups/:id/add_user", to: "groups#add_user_to_group", as: "add_user_to_group"

  patch "/tasks/:id/add_group", to: "tasks#add_group_to_task", as: "add_group_to_task"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :task_groups
  has_many :users, through: :user_groups
  has_many :tasks, through: :task_groups

  def tasks_completed
    self.tasks.filter {|task| task.status == "Completed"}
  end
  def tasks_in_progress
    self.tasks.filter {|task| task.status == "In Progress"}
  end
  def tasks_incomplete
    self.tasks.filter {|task| task.status == "Incomplete"}
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def new
        @group = Group.new
    end

    def create
        user = current_user
        group = user.groups.new(group_params)
        group.save
        redirect_to groups_path(group)
    end


    def show
        @group = Group.find(params[:id])
    end

    def index
        if params[:user_id]
            user = User.find[:user_id]
            @groups = user.groups
        else 
            @groups = Group.all
        end
    end

    def edit
        @group = Group.find(params[:id])
    end

    def update
        @group = Group.find(params[:id])

        if @group.update(group_params)
            redirect_to @group
        else
            render :edit
        end

    end

    def all_users
        @@users = User.all
    end

    # def add_users_to_group
    #     @group = Group.find(params[:id])
        
    # end

    def add_user_to_group
        puts params.inspect
        user = User.find_by(email: params["group"]["users"])
        p user
        @group = Group.find(params[:id])
        if @group.users.include?(user)
            redirect_to @group, notice: "You are already in this group"
        else
            @group.users << user
            redirect_to @group
        end
    end

    def delete

    end

    private
    def group_params
        params.require(:group).permit(:group_type, :users)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, url: add_user_to_group_path  do |f|%>
    <%= f.label :group_type %><br>
    <%= f.text_field :group_type %><br>
    <%= f.select :users, User.all.collect {|p| [p.email]} %>
    <%= f.submit %>
<% end %>

app/views/groups/edit.html.erb
<h1> Edit Group </h1>

<%= render "form", task: @task%>

app/views/groups/index.html.erb
<%@groups.each do |group|%>
<h2>
<%=link_to group.group_type, group_path(group)%>
</h2>

<%end%>

app/views/groups/new.html.erb
<%= render 'form' %>

app/views/groups/show.html.erb
<h1 class="title">
    <%= @group.group_type %>
</h1>

<h2>
    <% @group.users.each do |user|%>
    <%= user.email%>
    <% end %>
</h2>

<div class="FooterButtons">
    <%= link_to "EDIT", edit_group_path(@group)%>
    <br>
    <%= link_to "ALL GROUPS", groups_path %>
</div>