config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    authenticated do
      root to: 'tasks#index'
    end
    unauthenticated do
      root to: 'devise/sessions#new', as: nil
    end
  end  

  resources :groups do
    resources :tasks
  end

  resources :tasks do
    resources :groups
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" } 

  resources :users do
    resources :groups
  end

  resources :privacy_and_deletion_policy

  patch "/groups/:id/add_user", to: "groups#add_user_to_group", as: "add_user_to_group"

  patch "/tasks/:id/add_group", to: "tasks#add_group_to_task", as: "add_group_to_task"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= image_tag ("adina-logo-white_22x.png"), class: "adina_logo" %>

  <%= link_to "Sign out", destroy_user_session_path, method: :delete%>
    <%= yield %>
    <button id=new_button>
     <%= link_to "New Task", new_task_path %>
     </button>
    <div id="application_footer_links">
      <b>
      <%=  link_to "GROUPS", groups_path  %>
      &nbsp;
      <%= link_to "ALL TASKS", tasks_path %>
      </b>
    </div>
  </body>
</html>